/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true" />
/// <reference lib="esnext" />
/// <reference lib="webworker" />

const sw = self as unknown as ServiceWorkerGlobalScope;

import { build, files, version } from "$service-worker";

const CACHE = `cache-${version}`;

const ASSETS = [
	...build, // files generated by Vite / SvelteKit
	...files, // files in the static/ directory
];

// Install: precache the app shell
sw.addEventListener("install", (event) => {
	async function addFilesToCache() {
		const cache = await caches.open(CACHE);
		await cache.addAll(ASSETS);
	}

	event.waitUntil(addFilesToCache());
});

// Activate: clean up old caches
sw.addEventListener("activate", (event) => {
	async function deleteOldCaches() {
		for (const key of await caches.keys()) {
			if (key !== CACHE) {
				await caches.delete(key);
			}
		}
	}

	event.waitUntil(deleteOldCaches());
	// Take control of all pages immediately
	sw.clients.claim();
});

// Fetch: serve from cache or network
sw.addEventListener("fetch", (event) => {
	// Only handle GET requests
	if (event.request.method !== "GET") return;

	const url = new URL(event.request.url);

	// Skip non-HTTP(S) requests
	if (!url.protocol.startsWith("http")) return;

	// For API requests, always go to network
	if (url.pathname.startsWith("/api/")) return;

	async function respond(): Promise<Response> {
		const cache = await caches.open(CACHE);

		// Try the cache first for precached assets
		const cached = await cache.match(event.request);
		if (cached) return cached;

		// For attachment URLs (output files), use cache-on-access strategy
		if (url.pathname.includes("/output/")) {
			try {
				const response = await fetch(event.request);
				if (response.ok) {
					const responseToCache = response.clone();
					cache.put(event.request, responseToCache).catch(() => {});
					return response;
				}
				return response;
			} catch {
				return new Response("Offline", { status: 503 });
			}
		}

		// For navigation requests, serve the cached index page as fallback
		if (event.request.mode === "navigate") {
			try {
				return await fetch(event.request);
			} catch {
				const fallback = await cache.match("/");
				if (fallback) return fallback;
				return new Response("Offline", { status: 503 });
			}
		}

		// For everything else, try network, fall back to cache
		try {
			return await fetch(event.request);
		} catch {
			return new Response("Offline", { status: 503 });
		}
	}

	event.respondWith(respond());
});
